import * as config from '@lvce-editor/eslint-config'
import * as actions from '@lvce-editor/eslint-plugin-github-actions'

export default [
  ...config.default,
  ...config.recommendedVirtualDom,
  ...actions.default,
  {
    ignores: [
      '**/build/**',
      '**/coverage/**',
      '**/server/**',
      '**/.tmp/**',
      '**/memory/**',
      '**/extension-host-sub-worker/**',
      '**/test-integration/**',
      '**/test-integration-util/**',
      'dist',
      'coverage',
      'scripts',
      'rollup.config.js',
      'eslint.config.js',
      'packages/extension-host-worker/src/extensionHostWorkerMain.ts',
    ],
  },
  {
    rules: {
      '@typescript-eslint/require-await': 'off',
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/no-deprecated': 'off',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-confusing-void-expression': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      'unicorn/consistent-function-scoping': 'off',
      '@typescript-eslint/await-thenable': 'off',
      '@typescript-eslint/only-throw-error': 'off',
      '@typescript-eslint/prefer-readonly-parameter-types': 'off',
      '@typescript-eslint/unbound-method': 'off',
      'no-empty': 'off',
      '@typescript-eslint/no-redundant-type-constituents': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/prefer-promise-reject-errors': 'off',
      'jest/no-restricted-jest-methods': 'off',
      'no-restricted-syntax': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      'github-actions/ci-versions': 'off',
      '@cspell/spellchecker': 'off',
      'preserve-caught-error': 'off',
      'sonarjs/no-dead-store': 'off',
      'e2e/prefer-execute-extension-command': 'off',
      'e2e/prefer-import-meta-resolve': 'off',
      'sonarjs/prefer-specific-assertions': 'off',
      'sonarjs/super-linear-regex': 'off',
      'unicorn/no-break-in-nested-loop': 'off',
      'unicorn/no-declarations-before-early-exit': 'off',
      'unicorn/no-error-property-assignment': 'off',
      'unicorn/no-global-object-property-assignment': 'off',
      'unicorn/no-top-level-assignment-in-function': 'off',
      'unicorn/no-unreadable-for-of-expression': 'off',
      'unicorn/no-unsafe-string-replacement': 'off',
      'unicorn/no-useless-template-literals': 'off',
      'unicorn/prefer-array-from-async': 'off',
      'unicorn/prefer-array-from-map': 'off',
      'unicorn/prefer-await': 'off',
      'unicorn/prefer-continue': 'off',
      'unicorn/prefer-early-return': 'off',
      'unicorn/prefer-url-href': 'off',
    },
  },
  {
    files: ['packages/extension-host-worker/src/**/*.ts'],
    rules: {
      'virtual-dom/no-object-attribute-values': 'off',
      'virtual-dom/prefer-state-destructuring': 'off',
    },
  },
  {
    files: ['packages/**/test/**/*.ts'],
    rules: {
      'virtual-dom/no-object-attribute-values': 'off',
      'virtual-dom/prefer-constants': 'off',
      'virtual-dom/prefer-state-destructuring': 'off',
    },
  },
]
