export { getStatusBarItemProviderRegistrySnapshot } from './GetStatusBarItemProviderRegistrySnapshot.ts'
export { registerStatusBarItemProvider } from './RegisterStatusBarItemProvider.ts'
export { resetStatusBarItemProviderRegistry } from './ResetStatusBarItemProviderRegistry.ts'
export type { RegisteredStatusBarItemProvider } from './RegisteredStatusBarItemProvider.ts'
export type { StatusBarItem } from './StatusBarItem.ts'
export type { StatusBarItemProvider } from './StatusBarItemProvider.ts'
export type { StatusBarItemProviderHandle } from './StatusBarItemProviderHandle.ts'
export type { StatusBarItemProviderRegistrySnapshot } from './StatusBarItemProviderRegistrySnapshot.ts'
